<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PizzaController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/products', [PizzaController::class, 'pizza'])->name('products.pizza');
Route::post('/products/select', [ProductController::class, 'select'])->name('pizzas.select');

Route::get('/orders/{order}', [PedidoController::class, 'show'])->name('pedidos.show');
Route::post('/orders/{order}/confirm', [PedidoController::class, 'confirm'])->name('pedidos.confirm');

// Authentication routes generated by Laravel
Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

// Routes for products and orders (as mentioned in the previous response)
// ...

// Example logout route
Route::post('/logout', [Auth\LoginController::class, 'logout'])->name('logout');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
